"""Methodology — static documentation page."""
import streamlit as st

st.set_page_config(
    page_title="Methodology | TPR IP Viz",
    page_icon="📖",
    layout="wide",
)

st.title("📖 Methodology")

st.markdown("""
## Data Sources

### 1. WIPO IP Statistics (IPSTATS)

All IP filing and registration data is sourced from the
[WIPO IP Statistics Data Center](https://www.wipo.int/ipstats/) via the WIPO IPSTATS REST API.

| Indicator | WIPO Code | Breakdown |
|-----------|-----------|-----------|
| Patent Applications | 10 | Resident / Non-Resident |
| Patent Grants | 23 | Resident / Non-Resident |
| Trademark Applications | 30 | Resident / Non-Resident |
| Trademark Registrations | 47 | Resident / Non-Resident |
| Industrial Design Applications | 50 | Resident / Non-Resident |
| Industrial Design Registrations | 66 | Resident / Non-Resident |
| Utility Model Applications | 70 | Resident / Non-Resident |
| Utility Model Grants | 75 | Resident / Non-Resident |
| Geographical Indications | 503 | Total only |

**API endpoint:** `GET https://www.wipo.int/ipstats/api/data`
**Parameters:** `indicator`, `geo` (ISO alpha-2), `start`, `end`, `breakdown=ORIGIN`

---

### 2. WTO Timeseries API

IP services trade data is sourced from the [WTO Stats portal](https://stats.wto.org/)
via the WTO Timeseries REST API (subscription key required).

| Indicator | WTO Code | Description |
|-----------|----------|-------------|
| IP Service Exports | ITS_CS_AX6 | Charges for use of IP, n.i.e. — Credits (USD million) |
| IP Service Imports | ITS_CS_AM6 | Charges for use of IP, n.i.e. — Debits (USD million) |

**API endpoint:** `GET https://api.wto.org/timeseries/v1/data`
**Auth header:** `Ocp-Apim-Subscription-Key: <WTO_API_KEY>`

---

## Derived Indicators

| Metric | Formula | Notes |
|--------|---------|-------|
| **CAGR** | `(end / start)^(1/n) − 1` | Compound Annual Growth Rate |
| **Growth %** | `(end − start) / start × 100` | Period-over-period change |
| **Resident Share %** | `resident / total × 100` | Filing activity by origin |
| **Grant Rate %** | `grants / applications × 100` | Patent examination efficiency |
| **Registration Rate %** | `registrations / applications × 100` | TM/design examination |
| **Trade Balance** | `exports − imports` | IP services net position |
| **YoY Delta %** | `(t / t-1 − 1) × 100` | Year-on-year change |

---

## Excel Output

The Excel workbook is generated by:

1. Opening `templates/TPR_IP_Template.xlsx` (user-provided)
2. For each of 11 worksheets: clearing data rows (row 2+) and writing new data
3. Returning the populated workbook as a `.xlsx` download

Charts embedded in the template reference fixed cell ranges, so they auto-refresh when
the file is opened in Excel — no manual editing required.

**Fallback:** If the template file is absent, a plain data workbook is created from scratch
with styled headers but no chart objects.

---

## Caching

Raw API responses are cached to `data/raw/wipo/` and `data/raw/wto/` as JSON files
(keyed by `{country}_{indicator}_{start}_{end}.json`). This avoids repeated API calls
and speeds up subsequent runs.

The Streamlit dashboard additionally caches assembled profiles in memory for
**1 hour** (`@st.cache_data(ttl=3600)`). To force a refresh, use the Streamlit
menu (☰ → *Clear cache*) or delete the relevant JSON files from `data/raw/`.

---

## Country Coverage

All 164 WTO Members are available in the country selector, identified by their
ISO 3166-1 alpha-2 codes. Country names follow WTO official designations.

WIPO data availability varies by country, indicator, and year.
Missing values indicate non-reporting rather than zero activity.

---

## Limitations

1. **WIPO API format**: The WIPO IPSTATS REST API endpoint and response schema may change
   over time. If data fails to load, check the `WIPO_API_BASE` variable in `.env`.
2. **WTO API key**: IP services data requires a valid WTO Timeseries API subscription key.
   Register at [api.wto.org](https://api.wto.org/).
3. **GI coverage**: Geographical Indications data (WIPO indicator 503) is limited and
   may not cover the full 2010–2024 period for all countries.
4. **Template mapping**: The template writer maps sheets by position (index 1–11).
   If the template has a different sheet order or count, update `SHEET_CONFIG` in
   `src/excel/template_writer.py`.

---

## Contact

For questions about this tool, contact the **WTO Intellectual Property Division**.
For data queries: [WIPO Statistics](https://www.wipo.int/ipstats/) · [WTO Statistics](https://stats.wto.org/)
""")
